### PR TITLE
Fail to start application if ORI setup is incomplete

### LINKED ISSUE #29: App should fail on start if ORI setup is incomplete
Tried creating an instance, but I forgot to do steps 3 and 4 of installation:
```
3.
cp data/ori.csv.example data/ori.csv
4.
docker-compose build data
docker-compose run data
```

When I built the instance and ran it, the app splash page (for example) loaded fine. When I went to the dashboard, I got an "Ooops" page. The app's logs showed:

```
NameError (uninitialized constant Constants::CONTRACTING_ORIS):
  app/models/user.rb:77:in `contracting_oris'
  app/models/user.rb:81:in `allowed_oris'
  app/queries/get_all_incidents_query.rb:10:in `perform_query'
  app/queries/query.rb:6:in `run'
  app/queries/dashboard_incidents_query.rb:8:in `perform_query'
  app/queries/query.rb:6:in `run'
  app/controllers/incidents_controller.rb:155:in `set_incidents'
```

It took me some head scratching to figure this out. Instead, there should be an initializer function that throws a fit when the app boots, with an informative message, and the app should never start.

### PR DESCRIPTION
**Pull request by AlexNisnevich**
Fixes #29.

### CODE REVIEW

File: config/initializers/custom/ori.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# App should fail to start if ORI data isn't loaded.
+
+unless Rails.env.test?
```
Comment (wetchler) [inline config/initializers/custom/ori.rb:3]: Why don't we need this for testing? Wouldn't all the specs fail?

Comment (AlexNisnevich) [reply config/initializers/custom/ori.rb:3]: We mock these constants in tests. It's necessary so that the test results are consistent regardless of what ORIs are actually loaded.

**Review by wetchler — APPROVED** [review]
